<?php declare(strict_types=1);

namespace Plugin\LangUkrainian;

use App\Domain\Plugin\AbstractLanguagePlugin;
use Psr\Container\ContainerInterface;
use Slim\Psr7\Request;
use Slim\Psr7\Response;

class LangUkrainianPlugin extends AbstractLanguagePlugin
{
    const NAME = 'LangUkrainianPlugin';
    const TITLE = 'Українська мова';
    const AUTHOR = 'Sofiia Skladanivska;Aleksey Ilyin';
    const AUTHOR_SITE = 'https://getwebspace.org';
    const VERSION = '5.0.0';

    public function __construct(ContainerInterface $container)
    {
        parent::__construct($container);

        $this->addLocaleFromFile('uk-UA', __DIR__ . '/Locale/_.php');

        $this->addLocaleEditor('uk-UA', [
            "Type something" => "Напишіть щось",
            "Bold" => "Жирний",
            "Italic" => "Курсивний",
            "Underline" => "Підкреслений",
            "Strikethrough" => "Закреслений",
            "Insert" => "Вставити",
            "Delete" => "Видалити",
            "Cancel" => "Скасувати",
            "OK" => "OK",
            "Back" => "Назад",
            "Remove" => "Видалити",
            "More" => "Більше",
            "Update" => "Оновити",
            "Style" => "Стиль",
            "Font Family" => "Шрифт",
            "Font Size" => "Розмір шрифту",
            "Colors" => "Вибрати колір",
            "Background" => "Фон",
            "Text" => "Текст",
            "Paragraph Format" => "Параграф",
            "Normal" => "Звичайний",
            "Code" => "Код",
            "Heading 1" => "Заголовок 1",
            "Heading 2" => "Заголовок 2",
            "Heading 3" => "Заголовок 3",
            "Heading 4" => "Заголовок 4",
            "Heading 5" => "Заголовок 5",
            "Paragraph" => "Параграф (P)",
            "Layer" => "Шар (div)",
            "Preformatted" => "Форматований (pre)",
            "Paragraph Style" => "Вибрати оформлення параграфа",
            "Inline Style" => "Вибрати оформлення тексту",
            "Bordered" => "Обрамлення зверху і знизу",
            "Spaced" => "Збільшений інтервал букв",
            "Uppercase" => "З великих літер",
            "Gray" => "Сірий колір",
            "Red" => "Червоний колір",
            "Blue" => "Голубий колір",
            "Green" => "Зелений колір",
            "Align" => "Вирівнювання",
            "Align Left" => "По лівому краю",
            "Align Center" => "По центру",
            "Align Right" => "По правому краю",
            "Align Justify" => "По ширині",
            "None" => "За замовчуванням",
            "Ordered List" => "Нумерований список",
            "Unordered List" => "Маркований список",
            "Decrease Indent" => "Зменшити відступ",
            "Increase Indent" => "Збільшити відступ",
            "Insert Link" => "Вставити посилання",
            "Open in new tab" => "Відкрити в новій вкладці",
            "Open Link" => "Відкрити посилання",
            "Edit Link" => "Редагувати посилання",
            "Unlink" => "Видалити посилання",
            "Choose Link" => "Виберіть посилання",
            "Insert protected link" => "Вставити захищене посилання",
            "Insert Image" => "Вставити зображення",
            "Upload Image" => "Завантажити зображення",
            "By URL" => "Додати URL",
            "Browse" => "Огляд",
            "Drop image" => "Перетягніть зображення сюди",
            "or click" => "або натисніть",
            "Manage Images" => "Керування завантаженими зображеннями",
            "Loading" => "Завантаження",
            "Deleting" => "Видалення",
            "Tags" => "Ключові слова",
            "Are you sure? Image will be deleted." => "Ви впевнені? Зображення буде видалено.",
            "Replace" => "Замінити",
            "Uploading" => "Завантаження",
            "Loading image" => "Завантаження зображення",
            "Display" => "Параметри відображення",
            "Inline" => "Вбудовано в рядок",
            "Break Text" => "Окремий блок",
            "Alternate Text" => "Альтернативний текст",
            "Change Size" => "Змінити розміри",
            "Width" => "ширина",
            "Height" => "висота",
            "Something went wrong. Please try again." => "Щось пішло не так. Будь ласка, спробуйте ще раз.",
            "Borders" => "Додати межі",
            "Rounded" => "Закруглити кути",
            "Padded" => "Додати відступи",
            "Shadows" => "Додати тіні",
            "Embedded Code" => "HTML-код для відео",
            "Insert Table" => "Вставити таблицю",
            "Remove Table" => "Видалити таблицю",
            "Table Header" => "Заголовок таблиці",
            "Table Style" => "Оформлення таблиці",
            "Row" => "Керування рядками",
            "Insert row above" => "Вставити рядок зверху",
            "Insert row below" => "Вставити рядок знизу",
            "Delete row" => "Видалити рядок",
            "Column" => "Керування стовпцями",
            "Insert column before" => "Вставити стовпець зліва",
            "Insert column after" => "Вставити стовпець справа",
            "Delete column" => "Видалити стовпець",
            "Cell" => "Керування комірками",
            "Merge cells" => "Об'єднати комірки",
            "Horizontal split" => "Розділити по горизонталі",
            "Vertical split" => "Розділити по вертикалі",
            "Cell Background" => "Колір фону комірки",
            "Vertical Align" => "Вирівнювання по вертикалі",
            "Horizontal Align" => "Вирівнювання по горизонталі",
            "Top" => "Зверху",
            "Middle" => "По центру",
            "Bottom" => "Знизу",
            "Align Top" => "Вирівняти зверху",
            "Align Middle" => "Вирівняти по центру",
            "Align Bottom" => "Вирівняти знизу",
            "Cell Style" => "Оформлення комірки",
            "Solid Borders" => "Суцільні межі",
            "Dashed Borders" => "Пунктирні межі",
            "Alternate Rows" => "Змінні рядки",
            "Upload File" => "Завантажити файл",
            "Upload Video" => "Завантажити відео",
            "Drop file" => "Перетягніть файл сюди",
            "Drop video" => "Перетягніть відео сюди",
            "Break" => "Вставити рядок",
            "Subscript" => "Нижній індекс",
            "Superscript" => "Верхній індекс",
            "Fullscreen" => "Розгорнути на повний екран",
            "Insert Horizontal Line" => "Вставити горизонтальну лінію",
            "Clear Formatting" => "Видалити форматування",
            "Undo" => "Скасувати",
            "Redo" => "Повторити",
            "Select All" => "Виділити все",
            "Code View" => "HTML-код",
            "Insert audio" => "Вставити аудіотрек (mp3)",
            "Insert Video" => "Вставити відео",
            "Insert Quote" => "Вставити цитату",
            "Insert hidden text" => "Вставити схований текст",
            "Insert spoiler" => "Вставити спойлер",
            "Insert source code" => "Вставити вихідний код",
            "Page Navigation" => "Навігація по сторінках публікації",
            "Insert page breaks" => "Вставити розрив між сторінками",
            "Insert link to the page" => "Вставити посилання на сторінку",
            "Emoticons" => "Вставити смайлик",
            "Uploading files" => "Керування завантаженими файлами",
            "Link to the video" => "Введіть посилання на відео",
            "Description" => "Введіть опис",
            "Link to the poster" => "Введіть посилання на постер до відео",
            "Add to Playlist" => "Додати до плейлисту",
            "Link to the audio" => "Введіть посилання на аудіо",
            "Typographical Word Processing" => "Типографська обробка тексту",
            "Insert media link" => "Вставити контент з інших сервісів (Youtube, Twitter, Instagram)",
            "Word Paste Detected" => "Вставка з документа Word",
            "The pasted content is coming from a Microsoft Word document. Do you want to keep the format or clean it up?" => "Ви вставляєте контент з документа Word. Ви хочете залишити форматування тексту чи очистити його?",
            "Clean" => "Видалити форматування",
            "Keep" => "Залишити форматування",
            "Image URL" => "Посилання на зображення",
            "Alignment" => "Вирівнювання",
            "Not used" => "Не використовується",
            "Left" => "Ліворуч",
            "Right" => "Праворуч",
            "Center" => "По центру",
            "Quote" => "Цитата",
            "Increase" => "Збільшити",
            "Decrease" => "Зменшити",
            "Quick Insert" => "Швидка вставка",
            "Download PDF" => "Завантажити PDF",
            "Paste in a video URL" => "Вставте URL відео",
            "Image Caption" => "Підпис зображення",
            "Alternative Text" => "Альтернативний текст",
            "Inline Class" => "Вбудований клас",
            "Highlighted" => "Виділений",
            "Transparent" => "Прозорий",
            "Line Height" => "Висота рядка",
            "Default" => "За замовчуванням",
            "Single" => "Одинарний",
            "Double" => "Подвійний",
            "Special Characters" => "Спеціальні символи",
            "Help" => "Допомога",
        ]);

        $this->addLocaleTranslateLetters('uk-UA',
            [
                'А', 'Б', 'В', 'Г', 'Ґ', 'Д', 'Е', 'Є', 'Ж', 'З', 'И', 'І', 'Ї', 'Й', 'К', 'Л', 'М', 'Н', 'О', 'П',
                'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ю', 'Я', 'Ь', 'а', 'б', 'в', 'г', 'ґ', 'д', 'е',
                'є', 'ж', 'з', 'и', 'і', 'ї', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц',
                'ч', 'ш', 'щ', 'ю', 'я', 'ь',
            ],
            [
                'A', 'B', 'V', 'H', 'G', 'D', 'E', 'Ye', 'Zh', 'Z', 'Y', 'I', 'Yi', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                'R', 'S', 'T', 'U', 'F', 'X', 'C', 'Ch', 'Sh', 'Shh', 'Yu', 'Ya', '', 'a', 'b', 'v', 'h', 'g', 'd', 'e',
                'ye', 'zh', 'z', 'y', 'i', 'yi', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'f', 'x', 'c',
                'ch', 'sh', 'shh', 'yu', 'ya', '',
            ]
        );
    }
}
